#!/usr/bin/env bats
# Guards for the generated install.sh (scripts/build-install.sh).
#
# install.sh is assembled from install.sh.in + scripts/lib/*.sh. These tests fail
# if the committed install.sh drifts from its sources, or if the inlining leaks
# markers/source-guards into the generated file.

setup() {
    REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
}

@test "install.sh is in sync with install.sh.in + scripts/lib/*" {
    run bash "$REPO_ROOT/scripts/build-install.sh" --check
    [ "$status" -eq 0 ]
}

@test "generated install.sh has a shebang on line 1 and the AUTO-GENERATED banner" {
    [ "$(head -1 "$REPO_ROOT/install.sh")" = "#!/usr/bin/env bash" ]
    grep -q "AUTO-GENERATED by scripts/build-install.sh" "$REPO_ROOT/install.sh"
}

@test "generated install.sh contains no inline markers or source guards" {
    ! grep -q "@inline-begin\|@inline-end" "$REPO_ROOT/install.sh"
    ! grep -q "^# @inline scripts" "$REPO_ROOT/install.sh"
    ! grep -q "__DOTFILES_.*_SH" "$REPO_ROOT/install.sh"
}

@test "generated install.sh parses under bash" {
    run bash -n "$REPO_ROOT/install.sh"
    [ "$status" -eq 0 ]
}

@test "build-install.sh --check fails when a source changes but install.sh does not" {
    work="$BATS_TEST_TMPDIR/repo"
    mkdir -p "$work/scripts/lib"
    cp "$REPO_ROOT/install.sh" "$work/install.sh"
    cp "$REPO_ROOT/install.sh.in" "$work/install.sh.in"
    cp "$REPO_ROOT"/scripts/build-install.sh "$work/scripts/"
    cp "$REPO_ROOT"/scripts/lib/*.sh "$work/scripts/lib/"
    # Change a source (the driver) without regenerating install.sh.
    printf '# drift marker\n' >>"$work/install.sh.in"
    run bash "$work/scripts/build-install.sh" --check
    [ "$status" -ne 0 ]
}
