#!/usr/bin/env bash
# gen-commands.sh — rewrite the verb table in docs/commands.md from
# core/verbs.sh, between the two marker comments.
#
# The verb list lived in five hand-synced places and nothing checked four of
# them. Three are generated now — `chez help`, the completion feed and dispatch
# all read the table directly — and this makes the fourth generated too. What is
# left hand-written in that file is prose about *how* a verb behaves, which
# belongs to its feature's README and links there.
#
# Usage: scripts/ci/gen-commands.sh [REPO_ROOT]
#        scripts/ci/gen-commands.sh --check [REPO_ROOT]   # exit 1 if stale

set -euo pipefail

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

check=0
if [ "${1:-}" = "--check" ]; then
    check=1
    shift
fi
ROOT="${1:-$(cd "$_DIR/../.." && pwd)}"
DOC="$ROOT/docs/commands.md"

# shellcheck source=../../core/verbs.sh
. "$ROOT/core/verbs.sh"

START='<!-- verbs:start -->'
END='<!-- verbs:end -->'

render() {
    local group verb legacy module
    printf '%s\n' "$START"
    printf '<!-- Generated by scripts/ci/gen-commands.sh from core/verbs.sh. Do not edit. -->\n\n'
    while IFS= read -r group; do
        case "$group" in
            everyday) printf '### Everyday\n\n' ;;
            setup) printf '### Changing your setup\n\n' ;;
            maintenance) printf '### Maintenance\n\n' ;;
            hood) printf '### Under the hood\n\n' ;;
            *) printf '### %s\n\n' "$group" ;;
        esac
        printf '| Verb | Also known as | Module | What it does |\n|---|---|---|---|\n'
        while IFS= read -r verb; do
            legacy="$(verbs_legacy_name "$verb")"
            module="$(verbs_module "$verb")"
            case "$module" in "" | -) module="—" ;; *) module="\`$module\`" ;; esac
            printf '| `chez %s` | %s | %s | %s |\n' \
                "$verb" "${legacy:+\`$legacy\`}" "$module" "$(verbs_summary "$verb")"
        done < <(verbs_in_group "$group")
        printf '\n'
    done < <(verbs_groups)
    printf '%s\n' "$END"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
awk -v s="$START" -v e="$END" '
    $0 == s { skip = 1; print "@@BLOCK@@"; next }
    $0 == e { skip = 0; next }
    !skip   { print }
' "$DOC" >"$tmp"

grep -qF '@@BLOCK@@' "$tmp" || {
    printf 'gen-commands: %s has no %s marker\n' "$DOC" "$START" >&2
    exit 1
}

out="$(mktemp)"
trap 'rm -f "$tmp" "$out"' EXIT
while IFS= read -r line; do
    if [ "$line" = "@@BLOCK@@" ]; then render; else printf '%s\n' "$line"; fi
done <"$tmp" >"$out"

if [ "$check" -eq 1 ]; then
    if diff -q "$DOC" "$out" >/dev/null; then
        echo "gen-commands: docs/commands.md is current"
        exit 0
    fi
    printf 'gen-commands: docs/commands.md is stale — run scripts/ci/gen-commands.sh\n' >&2
    diff "$DOC" "$out" >&2 || true
    exit 1
fi

cp "$out" "$DOC"
echo "gen-commands: wrote the verb table into docs/commands.md"
