#!/usr/bin/env bash
# brew-bundle.sh — the Homebrew convergence engine.
#
# Single source of truth for "install exactly what the active Brewfile modules
# declare, with per-item progress and a heartbeat on slow downloads." Sourced by
# .chezmoiscripts/run_after_02-brew-bundle.sh.tmpl (which selects the modules for
# the active profile/features and prints the high-level plan); never executed
# directly. The pure helpers are unit-tested by tests/brew-bundle.bats.
#
# Design rules (see docs/lifecycle.md):
#   - State-based, not hash-gated: callers run this on EVERY apply. bb_modules_
#     satisfied is the fast short-circuit so a clean machine stays quick.
#   - Continue-on-error: one flaky cask never blocks the rest. Failures are
#     collected in BB_FAILURES and summarised by the caller; the apply proceeds.
#   - bash 3.2 only (macOS stock): no declare -A, ${var^^}, mapfile, or
#     fractional read -t. Guard array access under set -u with length checks.
#   - DRY_RUN=1 prints the state-changing brew commands instead of running them,
#     so the engine can be dry-driven and unit-tested without touching the system.
#
# Public API:
#   bb_init                          create the temp workdir + EXIT-clean trap
#   bb_modules_satisfied FILE...     0 if every active module is already present
#   bundle_one LBL FILE MS MT IS IT  install one module's entries (see below)
#   BB_FAILURES                      array of "label: entry (rc=N)" failure lines
# Internals kept public for testing: is_bundle_line, entry_name, count_bundle_lines.

# Source guard so re-sourcing is cheap and safe.
[ -n "${__DOTFILES_BREW_BUNDLE_SH:-}" ] && return 0
__DOTFILES_BREW_BUNDLE_SH=1

BB_TMP_DIR=""
BB_HEARTBEAT_PID=""
# Collected install failures, one human line each. Callers summarise at the end.
BB_FAILURES=()

# ─── Lifecycle ────────────────────────────────────────────────────────────────

# bb_init — make the per-run scratch dir and ensure it's cleaned up on exit.
bb_init() {
    [ -n "$BB_TMP_DIR" ] && return 0
    BB_TMP_DIR="$(mktemp -d)"
    trap bb_cleanup EXIT
}

bb_cleanup() {
    bb_stop_heartbeat
    [ -n "$BB_TMP_DIR" ] && rm -rf "$BB_TMP_DIR"
    BB_TMP_DIR=""
}

# ─── Heartbeat (so long silent downloads don't look hung) ─────────────────────

# bb_start_heartbeat LABEL — print "(elapsed)" every 30s until stopped. The
# child self-terminates within ~2s of its parent dying, so it can't outlive us.
bb_start_heartbeat() {
    local label="$1"
    local parent_pid=$$
    local start_ts
    start_ts="$(date +%s)"
    (
        local since_msg=0
        while kill -0 "$parent_pid" 2>/dev/null; do
            sleep 2
            since_msg=$((since_msg + 2))
            if [ "$since_msg" -ge 30 ]; then
                local now elapsed mins secs
                now="$(date +%s)"
                elapsed=$((now - start_ts))
                mins=$((elapsed / 60))
                secs=$((elapsed % 60))
                printf "  … still working on %s — %dm%02ds elapsed\n" "$label" "$mins" "$secs"
                since_msg=0
            fi
        done
    ) &
    BB_HEARTBEAT_PID=$!
}

bb_stop_heartbeat() {
    if [ -n "$BB_HEARTBEAT_PID" ]; then
        kill "$BB_HEARTBEAT_PID" 2>/dev/null
        # Reap immediately so the shell's async "Terminated" job notice never
        # leaks into the apply output.
        wait "$BB_HEARTBEAT_PID" 2>/dev/null || true
    fi
    BB_HEARTBEAT_PID=""
}

# ─── Pure helpers (unit-tested) ───────────────────────────────────────────────

# is_bundle_line LINE — true if LINE is an actionable brew bundle directive.
is_bundle_line() {
    case "$1" in
        tap\ * | brew\ * | cask\ * | mas\ *) return 0 ;;
        *) return 1 ;;
    esac
}

# entry_name LINE — "kind name" for display, e.g. 'cask "raycast"' -> "cask raycast".
entry_name() {
    local line="$1" kind name
    kind="${line%%[[:space:]]*}"
    name="$(printf '%s\n' "$line" | sed -n 's/^[[:space:]]*[[:alpha:]][[:alpha:]]*[[:space:]]*"\([^"]*\)".*/\1/p')"
    [ -n "$name" ] || name="$line"
    printf '%s %s' "$kind" "$name"
}

# count_bundle_lines FILE — number of actionable directives in FILE (0 if absent).
count_bundle_lines() {
    local file="$1" count=0 line
    [ -f "$file" ] || {
        printf '0'
        return
    }
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line#"${line%%[![:space:]]*}"}"
        is_bundle_line "$line" && count=$((count + 1))
    done <"$file"
    printf '%s' "$count"
}

# ─── Brewfile assembly + checks ───────────────────────────────────────────────

# write_unit_brewfile TARGET ENTRY [TAP_LINE...] — single-entry Brewfile, with any
# taps the entry needs prepended so it resolves on its own.
write_unit_brewfile() {
    local target="$1" entry="$2"
    shift 2
    local tap_line
    {
        printf '# Generated by dotfiles brew-bundle split installer.\n'
        for tap_line in "$@"; do
            printf '%s\n' "$tap_line"
        done
        printf '%s\n' "$entry"
    } >"$target"
}

# bb_modules_satisfied FILE... — fast short-circuit. Return 0 when every entry
# declared across the given module files is already PRESENT (installed/tapped).
#
# Deliberately a presence check, NOT `brew bundle check`: bundle check also flags
# merely-outdated packages as unsatisfied, which would make the short-circuit
# almost never fire and turn every apply into a surprise upgrade run. Freshness
# is `chezbump`'s job; convergence only guarantees presence. Three `brew` calls
# total (formulae, casks, taps) then pure-bash membership, so it's fast
# regardless of module size. Under DRY_RUN, always report "not satisfied" so the
# install plan is exercised.
bb_modules_satisfied() {
    [ "${DRY_RUN:-0}" = "1" ] && return 1

    local installed_formulae installed_casks installed_taps
    installed_formulae="$(brew list --formula -1 2>/dev/null)"
    installed_casks="$(brew list --cask -1 2>/dev/null)"
    installed_taps="$(brew tap 2>/dev/null)"

    local f line display kind name leaf
    for f in "$@"; do
        [ -f "$f" ] || continue
        while IFS= read -r line || [ -n "$line" ]; do
            line="${line#"${line%%[![:space:]]*}"}"
            is_bundle_line "$line" || continue
            display="$(entry_name "$line")"
            kind="${display%% *}"
            name="${display#* }"
            case "$kind" in
                tap)
                    # brew normalises taps to lowercase (e.g. Azure/kubelogin →
                    # azure/kubelogin), so compare case-insensitively.
                    printf '%s\n' "$installed_taps" | grep -qixF "$name" || return 1
                    ;;
                brew)
                    # A tapped formula (org/tap/name) lists under its leaf name.
                    leaf="${name##*/}"
                    printf '%s\n' "$installed_formulae" | grep -qxF "$leaf" || return 1
                    ;;
                cask)
                    printf '%s\n' "$installed_casks" | grep -qxF "$name" || return 1
                    ;;
                *) : ;; # mas/unknown: not used by these Brewfiles
            esac
        done <"$f"
    done
    return 0
}

# ─── The per-item installer (continue-on-error) ───────────────────────────────

# bundle_one LABEL FILE MODULE_STEP MODULE_TOTAL ITEM_START ITEM_TOTAL
# Install each entry in FILE one at a time so a fresh install is recoverable and
# large casks show real progress. On a failing entry: record it in BB_FAILURES
# and KEEP GOING (so e.g. a broken cask never blocks the ones after it). Always
# returns 0; callers inspect BB_FAILURES.
bundle_one() {
    local label="$1" file="$2" module_step="$3" module_total="$4" item_start="$5" item_total="$6"
    if [ ! -f "$file" ]; then
        echo "! $label: $file not found, skipping"
        return 0
    fi
    bb_init

    local module_items module_start module_end module_elapsed module_mins module_secs
    module_items="$(count_bundle_lines "$file")"
    printf "→ Module %d/%d: %s (%s, %s item(s))\n" "$module_step" "$module_total" "$label" "$(basename "$file")" "$module_items"
    [ "$module_items" -gt 0 ] || {
        echo "✓ Module $module_step/$module_total: $label has no active entries"
        return 0
    }

    local active_taps=()
    local line display item_step item_file start_ts end_ts elapsed mins secs rc
    item_step="$item_start"
    module_start="$(date +%s)"

    while IFS= read -r line || [ -n "$line" ]; do
        line="${line#"${line%%[![:space:]]*}"}"
        is_bundle_line "$line" || continue

        display="$(entry_name "$line")"
        item_file="$BB_TMP_DIR/brew-bundle-${item_step}.Brewfile"
        if [ ${#active_taps[@]} -gt 0 ]; then
            write_unit_brewfile "$item_file" "$line" "${active_taps[@]}"
        else
            write_unit_brewfile "$item_file" "$line"
        fi

        printf "→ %d/%d  %s: %s\n" "$item_step" "$item_total" "$label" "$display"
        start_ts="$(date +%s)"
        bb_start_heartbeat "$display"
        rc=0
        if [ "${DRY_RUN:-0}" = "1" ]; then
            echo "  DRY-RUN: brew bundle install --file=$item_file"
        else
            brew bundle install --file="$item_file" || rc=$?
        fi
        bb_stop_heartbeat

        end_ts="$(date +%s)"
        elapsed=$((end_ts - start_ts))
        mins=$((elapsed / 60))
        secs=$((elapsed % 60))
        if [ "$rc" -eq 0 ]; then
            printf "✓ %d/%d  %s: %s done in %dm%02ds\n" "$item_step" "$item_total" "$label" "$display" "$mins" "$secs"
        else
            printf "✗ %d/%d  %s: %s failed after %dm%02ds (rc=%d) — continuing\n" "$item_step" "$item_total" "$label" "$display" "$mins" "$secs" "$rc"
            BB_FAILURES+=("$label: $display (rc=$rc)")
        fi

        case "$line" in
            tap\ *) active_taps+=("$line") ;;
        esac
        item_step=$((item_step + 1))
    done <"$file"

    module_end="$(date +%s)"
    module_elapsed=$((module_end - module_start))
    module_mins=$((module_elapsed / 60))
    module_secs=$((module_elapsed % 60))
    printf "✓ Module %d/%d: %s complete in %dm%02ds\n" "$module_step" "$module_total" "$label" "$module_mins" "$module_secs"
    return 0
}
