#!/usr/bin/env bash
# build-install.sh — assemble the top-level install.sh from its sources.
#
# install.sh is the fresh-Mac bootstrap. It runs via `curl | bash` BEFORE this
# repo exists on disk, so unlike every other script it cannot `source
# scripts/lib/*`. To avoid hand-maintaining a second verbatim copy of the ~500-
# line UI engine (which had already drifted from ui.sh), install.sh is a
# GENERATED artifact: the maintained driver lives in install.sh.in, and this
# script expands each `# @inline <path>` line into the region between that lib's
# `# @inline-begin`/`# @inline-end` markers. The engine therefore has exactly one
# source of truth (scripts/lib/*.sh); install.sh just embeds it.
#
# Usage:
#   bash scripts/build-install.sh            # (re)generate install.sh
#   bash scripts/build-install.sh --check    # verify install.sh is up to date
#
# CI runs --check so a change to a lib or install.sh.in that isn't regenerated
# fails the build instead of silently shipping a stale install.sh.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
IN="$ROOT/install.sh.in"
OUT="$ROOT/install.sh"

CHECK=0
case "${1:-}" in
    --check) CHECK=1 ;;
    "") ;;
    *)
        echo "build-install.sh: unknown option: $1" >&2
        echo "usage: bash scripts/build-install.sh [--check]" >&2
        exit 2
        ;;
esac

# extract_inline FILE — print the lines strictly between the @inline markers.
extract_inline() {
    local file="$1" in_region=0 line
    if [ ! -r "$file" ]; then
        echo "build-install.sh: cannot read inline source: $file" >&2
        exit 1
    fi
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            '# @inline-begin')
                in_region=1
                continue
                ;;
            '# @inline-end')
                in_region=0
                continue
                ;;
        esac
        [ "$in_region" = 1 ] && printf '%s\n' "$line"
    done <"$file"
}

# generate — stream install.sh.in, injecting the generated banner after the
# shebang and expanding each `# @inline <path>` line.
generate() {
    local line first=1 path
    while IFS= read -r line || [ -n "$line" ]; do
        if [ "$first" = 1 ]; then
            printf '%s\n' "$line" # shebang, verbatim as line 1
            cat <<'BANNER'
#
# !!! AUTO-GENERATED by scripts/build-install.sh - DO NOT EDIT THIS FILE. !!!
#
# The engine (colors/glyphs/prompts/data readers) is inlined from
# scripts/lib/*.sh; the driver lives in install.sh.in. To change install.sh,
# edit one of those and re-run:
#
#     bash scripts/build-install.sh
#
# CI (build-install.sh --check) fails if this file is out of sync with them.
BANNER
            first=0
            continue
        fi
        # A directive is exactly `# @inline <path>` where <path> is a single
        # space-free token spanning the rest of the line — so prose that merely
        # mentions "@inline" (with following words) is left as an ordinary comment.
        if [[ "$line" =~ ^#\ @inline\ ([^[:space:]]+)$ ]]; then
            path="${BASH_REMATCH[1]}"
            printf '# ---- inlined from %s (edit there, not here) ----\n' "$path"
            extract_inline "$ROOT/$path"
            printf '# ---- end %s ----\n' "$path"
        else
            printf '%s\n' "$line"
        fi
    done <"$IN"
}

if [ ! -r "$IN" ]; then
    echo "build-install.sh: missing driver source: $IN" >&2
    exit 1
fi

generated="$(generate)"

if [ "$CHECK" = 1 ]; then
    if [ ! -r "$OUT" ]; then
        echo "build-install.sh: $OUT does not exist — run: bash scripts/build-install.sh" >&2
        exit 1
    fi
    if printf '%s\n' "$generated" | diff -u "$OUT" - >/dev/null 2>&1; then
        echo "install.sh is up to date with install.sh.in + scripts/lib/*"
        exit 0
    fi
    echo "install.sh is STALE — regenerate with: bash scripts/build-install.sh" >&2
    printf '%s\n' "$generated" | diff -u "$OUT" - || true
    exit 1
fi

printf '%s\n' "$generated" >"$OUT"
chmod +x "$OUT"
echo "wrote $OUT"
