#!/usr/bin/env bash
#
# Generate ~/.config/git/config.local, the machine-local half of the git
# config. See modules/git/README.md.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

name=$(cfg_get 'user.name')
email=$(cfg_get 'user.email')
signingkey=$(module_setting git signingkey '')

dest="$HOME/.config/git/config.local"

# Signing and verifying are two settings, and having only the first is the
# quiet half-configuration git ships with: every commit gets a signature and
# `git log --show-signature` answers "No signature".
allow="$HOME/.config/git/allowed_signers"

# The ssh module does NOT cover signing: git shells out to gpg.ssh.program,
# which defaults to `ssh-keygen -Y sign`, and ssh-keygen never reads
# ~/.ssh/config. Only 1Password's own signer reaches the vault.
opsign=${DOT_OP_SSH_SIGN:-/Applications/1Password.app/Contents/MacOS/op-ssh-sign}

# Absolute, because git run from a GUI inherits no shell PATH. Only written
# when VS Code is installed, or every commit fails on a missing editor.
code=${DOT_CODE_BIN:-/opt/homebrew/bin/code}

if [[ -z $name || -z $email ]]; then
  warn git 'user.name or user.email is empty in config.toml -- skipping config.local'
  exit 0
fi

# Decided out here: `warn` goes to stderr, but inside the generator below
# stdout IS config.local. All three signing keys or none -- `gpgsign = true`
# with no reachable signer aborts every commit. Above the dry-run branch, so a
# preview says the same words as the run it previews.
sign=0
if [[ -n $signingkey ]]; then
  if [[ -x $opsign ]]; then
    sign=1
  else
    warn git 'commit signing off -- 1Password is not installed yet; re-run `dot apply`'
  fi
fi

# An allowed_signers line is "<principal> <keytype> <base64>", so only a
# LITERAL public key can go in one. git also accepts a path in signingkey, and
# writing that produces a file ssh-keygen refuses to read at all -- which git
# reports as a verification failure, not as a bad config.
verify=0
if ((sign)); then
  if [[ $signingkey == ssh-*' '* || $signingkey == sk-*' '* ]]; then
    verify=1
  else
    warn git 'signature verification off -- signingkey is not a literal public key'
    dim 'put the key itself in config.toml, not a path to it'
  fi
fi

# A generated file the repo has stopped accounting for is one only uninstall.sh
# would ever find again. The header is the same proof of ownership remove.sh
# greps for (tests/git.bats holds the literals together), so a hand-written
# allowed_signers that predates this module is left alone. fs_discard gates on
# DOT_DRY_RUN itself, which is why it sits above the branch.
if ((verify == 0)) && [[ -f $allow ]] &&
  grep -q 'Generated by the git module' "$allow"; then
  fs_discard "$allow"
fi

# The same ownership test pointing the other way: `allowed_signers` is a
# conventional name, so a file here may predate this module, and truncating it
# is the wholesale rewrite of a user's file the root CLAUDE.md forbids.
# config.local may still point git at it, and doctor.sh judges whether it names
# the key.
own=1
if ((verify)) && [[ -f $allow ]] &&
  ! grep -q 'Generated by the git module' "$allow"; then
  own=0
  info keep "${allow/#$HOME/\~} -- not generated by this repo"
fi

if [[ $DOT_DRY_RUN == 1 ]]; then
  info write "${dest/#$HOME/\~}"
  if ((verify && own)); then info write "${allow/#$HOME/\~}"; fi
  exit 0
fi

# git's config language: `#` and `;` start a comment and a bare `"` is
# stripped, silently. Inside quotes only `"` and `\` need escaping.
q() {
  local v=$1
  v=${v//\\/\\\\}
  v=${v//\"/\\\"}
  printf '"%s"' "$v"
}

mkdir -p "$(dirname "$dest")"

# The same header both files carry; remove.sh greps for it as the proof that
# this repo wrote them.
header() {
  printf '# Generated by the git module. Edits here are overwritten.\n'
  printf '# Change the values in ~/.config/dotfiles/config.toml instead.\n'
}

if ((verify && own)); then
  {
    header
    printf '%s %s\n' "$email" "$signingkey"
  } >"$allow"
fi

{
  header
  printf '\n'
  printf '[user]\n\tname = %s\n\temail = %s\n' "$(q "$name")" "$(q "$email")"
  if ((sign)); then
    printf '\tsigningkey = %s\n\n' "$(q "$signingkey")"
    printf '[gpg]\n\tformat = ssh\n\n'
    printf '[gpg "ssh"]\n\tprogram = %s\n' "$(q "$opsign")"
    # Absolute, like the signer above it: git run from a GUI expands no ~.
    if ((verify)); then printf '\tallowedSignersFile = %s\n' "$(q "$allow")"; fi
    printf '\n[commit]\n\tgpgsign = true\n'
  fi
  if [[ -x $code ]]; then
    printf '\n[core]\n\teditor = %s\n' "$(q "$code --wait")"
  fi
} >"$dest"

ok git "identity: $name <$email>"
