#!/usr/bin/env bash
#
# config.local is written, not linked, so the symlink sweep cannot see it.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

# take PATH -- the header is the proof of ownership: both names are
# conventional, and a hand-written one may predate the module. One function so
# the literal appears once; tests/git.bats reads it back out of this line.
take() {
  local dest=$1
  if [[ -f $dest ]] && grep -q 'Generated by the git module' "$dest"; then
    fs_discard "$dest"
  elif [[ -e $dest ]]; then
    warn 'left alone' "${dest/#$HOME/\~} (not generated by this repo)"
  fi
}

take "$HOME/.config/git/config.local"
take "$HOME/.config/git/allowed_signers"
